Tests: Add VEDRIVE support
Thanks to @bobbimanners and @ksherlock and of course @ADTPro for
making this possible.

diff --git a/bin/mametest b/bin/mametest
--- a/bin/mametest
+++ b/bin/mametest
@@ -127,6 +127,35 @@ export UNFORMATTED_IMG="$TMPDIR/disks/unformatted.2mg"
 cp "res/unformatted.2mg" "$UNFORMATTED_IMG"
 
 # --------------------------------------------------
+# VEDrive
+
+# From https://github.com/bobbimanners/ProDOS-Utils/
+
+VESERVER="../ProDOS-Utils/veserver.py"
+VESERVERARGS=""
+if [ -n "$VEDISK1" ]; then
+  ext="${VEDISK1##*.}"
+  target="$TMPDIR/disks/vdisk1.${ext}"
+  cp "$VEDISK1" "$target"
+  VESERVERARGS="$VESERVERARGS --disk1=$target"
+fi
+if [ -n "$VEDISK2" ]; then
+  ext="${VEDISK2##*.}"
+  target="$TMPDIR/disks/vdisk2.${ext}"
+  cp "$VEDISK2" "$target"
+  VESERVERARGS="$VESERVERARGS --disk2=$target"
+fi
+if [ -n "$VESERVERARGS" ]; then
+  if [ ! -x "$VESERVER" ]; then
+    echo "$VESERVER not found!" 1>&2
+    exit 1
+  fi
+  ../ProDOS-Utils/veserver.py $VESERVERARGS >/dev/null &
+  VESERVER_PID=$!
+  trap "kill $VESERVER_PID" EXIT
+fi
+
+# --------------------------------------------------
 # Symbols
 
 DESKTOP_SYMBOLS=""
